//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"categoria")]
    public partial class Categoria : XPLiteObject
    {
        int fIdCategoria;
        [Key(true)]
        public int IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<int>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        string fDescripcion;
        [Size(50)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        sbyte fEstado;
        [ColumnDefaultValue(1)]
        public sbyte Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<sbyte>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"ProductoReferencesCategoria")]
        public XPCollection<Producto> Productoes { get { return GetCollection<Producto>(nameof(Productoes)); } }
    }

}
