//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"cliente")]
    public partial class Cliente : XPLiteObject
    {
        int fIdCliente;
        [Key(true)]
        public int IdCliente
        {
            get { return fIdCliente; }
            set { SetPropertyValue<int>(nameof(IdCliente), ref fIdCliente, value); }
        }
        string fDocumento;
        [Indexed(Name = @"Documento", Unique = true)]
        [Size(50)]
        public string Documento
        {
            get { return fDocumento; }
            set { SetPropertyValue<string>(nameof(Documento), ref fDocumento, value); }
        }
        string fNombreCompleto;
        [Size(50)]
        public string NombreCompleto
        {
            get { return fNombreCompleto; }
            set { SetPropertyValue<string>(nameof(NombreCompleto), ref fNombreCompleto, value); }
        }
        string fCorreo;
        [Indexed(Name = @"Correo", Unique = true)]
        [Size(80)]
        public string Correo
        {
            get { return fCorreo; }
            set { SetPropertyValue<string>(nameof(Correo), ref fCorreo, value); }
        }
        string fTelefono;
        [Size(50)]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        sbyte fEstado;
        [ColumnDefaultValue(1)]
        public sbyte Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<sbyte>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"VentaReferencesCliente")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
