//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"compra")]
    public partial class Compra : XPLiteObject
    {
        int fIdCompra;
        [Key(true)]
        public int IdCompra
        {
            get { return fIdCompra; }
            set { SetPropertyValue<int>(nameof(IdCompra), ref fIdCompra, value); }
        }
        Usuario fIdUsuario;
        [Association(@"CompraReferencesUsuario")]
        public Usuario IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<Usuario>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        Proveedor fIdProveedor;
        [Association(@"CompraReferencesProveedor")]
        public Proveedor IdProveedor
        {
            get { return fIdProveedor; }
            set { SetPropertyValue<Proveedor>(nameof(IdProveedor), ref fIdProveedor, value); }
        }
        decimal fMontoTotal;
        public decimal MontoTotal
        {
            get { return fMontoTotal; }
            set { SetPropertyValue<decimal>(nameof(MontoTotal), ref fMontoTotal, value); }
        }
        [Association(@"Detalle_compraReferencesCompra")]
        public XPCollection<Detalle_compra> Detalle_compras { get { return GetCollection<Detalle_compra>(nameof(Detalle_compras)); } }
    }

}
