//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"detalle_compra")]
    public partial class Detalle_compra : XPLiteObject
    {
        int fIdDetalleCompra;
        [Key(true)]
        public int IdDetalleCompra
        {
            get { return fIdDetalleCompra; }
            set { SetPropertyValue<int>(nameof(IdDetalleCompra), ref fIdDetalleCompra, value); }
        }
        Compra fIdCompra;
        [Association(@"Detalle_compraReferencesCompra")]
        public Compra IdCompra
        {
            get { return fIdCompra; }
            set { SetPropertyValue<Compra>(nameof(IdCompra), ref fIdCompra, value); }
        }
        Producto fIdProducto;
        [Association(@"Detalle_compraReferencesProducto")]
        public Producto IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<Producto>(nameof(IdProducto), ref fIdProducto, value); }
        }
        decimal fPrecioCompra;
        [ColumnDefaultValue(0.00)]
        public decimal PrecioCompra
        {
            get { return fPrecioCompra; }
            set { SetPropertyValue<decimal>(nameof(PrecioCompra), ref fPrecioCompra, value); }
        }
        decimal fPrecioVenta;
        [ColumnDefaultValue(0.00)]
        public decimal PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<decimal>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fMontoTotal;
        public decimal MontoTotal
        {
            get { return fMontoTotal; }
            set { SetPropertyValue<decimal>(nameof(MontoTotal), ref fMontoTotal, value); }
        }
    }

}
