//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"detalle_venta")]
    public partial class Detalle_venta : XPLiteObject
    {
        int fIdDetalleVenta;
        [Key(true)]
        public int IdDetalleVenta
        {
            get { return fIdDetalleVenta; }
            set { SetPropertyValue<int>(nameof(IdDetalleVenta), ref fIdDetalleVenta, value); }
        }
        Venta fIdVenta;
        [Association(@"Detalle_ventaReferencesVenta")]
        public Venta IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<Venta>(nameof(IdVenta), ref fIdVenta, value); }
        }
        Producto fIdProducto;
        [Association(@"Detalle_ventaReferencesProducto")]
        public Producto IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<Producto>(nameof(IdProducto), ref fIdProducto, value); }
        }
        decimal fPrecioVenta;
        public decimal PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<decimal>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fSubTotal;
        public decimal SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<decimal>(nameof(SubTotal), ref fSubTotal, value); }
        }
    }

}
