//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"medida")]
    public partial class Medida : XPLiteObject
    {
        int fIdMedida;
        [Key(true)]
        public int IdMedida
        {
            get { return fIdMedida; }
            set { SetPropertyValue<int>(nameof(IdMedida), ref fIdMedida, value); }
        }
        string fDescripcion;
        [Size(50)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        string fAbreviatura;
        [Size(10)]
        public string Abreviatura
        {
            get { return fAbreviatura; }
            set { SetPropertyValue<string>(nameof(Abreviatura), ref fAbreviatura, value); }
        }
        [Association(@"ProductoReferencesMedida")]
        public XPCollection<Producto> Productoes { get { return GetCollection<Producto>(nameof(Productoes)); } }
    }

}
