//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"producto")]
    public partial class Producto : XPLiteObject
    {
        int fIdProducto;
        [Key(true)]
        public int IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<int>(nameof(IdProducto), ref fIdProducto, value); }
        }
        string fCodigo;
        [Size(50)]
        public string Codigo
        {
            get { return fCodigo; }
            set { SetPropertyValue<string>(nameof(Codigo), ref fCodigo, value); }
        }
        string fNombre;
        [Size(50)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDescripcion;
        [Size(50)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        Categoria fIdCategoria;
        [Association(@"ProductoReferencesCategoria")]
        public Categoria IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<Categoria>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        int fStock;
        [ColumnDefaultValue(0)]
        public int Stock
        {
            get { return fStock; }
            set { SetPropertyValue<int>(nameof(Stock), ref fStock, value); }
        }
        decimal fPrecioCompra;
        [ColumnDefaultValue(0.00)]
        public decimal PrecioCompra
        {
            get { return fPrecioCompra; }
            set { SetPropertyValue<decimal>(nameof(PrecioCompra), ref fPrecioCompra, value); }
        }
        decimal fPrecioVenta;
        [ColumnDefaultValue(0.00)]
        public decimal PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<decimal>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        sbyte fEstado;
        [ColumnDefaultValue(1)]
        public sbyte Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<sbyte>(nameof(Estado), ref fEstado, value); }
        }
        Medida fIdMedida;
        [Association(@"ProductoReferencesMedida")]
        public Medida IdMedida
        {
            get { return fIdMedida; }
            set { SetPropertyValue<Medida>(nameof(IdMedida), ref fIdMedida, value); }
        }
        [Association(@"Detalle_compraReferencesProducto")]
        public XPCollection<Detalle_compra> Detalle_compras { get { return GetCollection<Detalle_compra>(nameof(Detalle_compras)); } }
        [Association(@"Detalle_ventaReferencesProducto")]
        public XPCollection<Detalle_venta> Detalle_ventas { get { return GetCollection<Detalle_venta>(nameof(Detalle_ventas)); } }
    }

}
