//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"proveedor")]
    public partial class Proveedor : XPLiteObject
    {
        int fIdProveedor;
        [Key(true)]
        public int IdProveedor
        {
            get { return fIdProveedor; }
            set { SetPropertyValue<int>(nameof(IdProveedor), ref fIdProveedor, value); }
        }
        string fDocumento;
        [Indexed(Name = @"Documento", Unique = true)]
        [Size(50)]
        public string Documento
        {
            get { return fDocumento; }
            set { SetPropertyValue<string>(nameof(Documento), ref fDocumento, value); }
        }
        string fRazonSocial;
        [Size(50)]
        public string RazonSocial
        {
            get { return fRazonSocial; }
            set { SetPropertyValue<string>(nameof(RazonSocial), ref fRazonSocial, value); }
        }
        string fCorreo;
        [Indexed(Name = @"Correo", Unique = true)]
        [Size(80)]
        public string Correo
        {
            get { return fCorreo; }
            set { SetPropertyValue<string>(nameof(Correo), ref fCorreo, value); }
        }
        string fTelefono;
        [Size(50)]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        sbyte fEstado;
        [ColumnDefaultValue(1)]
        public sbyte Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<sbyte>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"CompraReferencesProveedor")]
        public XPCollection<Compra> Compras { get { return GetCollection<Compra>(nameof(Compras)); } }
    }

}
