//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"usuario")]
    public partial class Usuario : XPLiteObject
    {
        int fIdUsuario;
        [Key(true)]
        public int IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<int>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        string fNombreCompleto;
        [Size(50)]
        public string NombreCompleto
        {
            get { return fNombreCompleto; }
            set { SetPropertyValue<string>(nameof(NombreCompleto), ref fNombreCompleto, value); }
        }
        string fUsername;
        [Size(50)]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        string fPwd;
        [Size(60)]
        public string Pwd
        {
            get { return fPwd; }
            set { SetPropertyValue<string>(nameof(Pwd), ref fPwd, value); }
        }
        Rol fIdRol;
        [Association(@"UsuarioReferencesRol")]
        public Rol IdRol
        {
            get { return fIdRol; }
            set { SetPropertyValue<Rol>(nameof(IdRol), ref fIdRol, value); }
        }
        sbyte fEstado;
        [ColumnDefaultValue(1)]
        public sbyte Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<sbyte>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"CompraReferencesUsuario")]
        public XPCollection<Compra> Compras { get { return GetCollection<Compra>(nameof(Compras)); } }
        [Association(@"VentaReferencesUsuario")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
