//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FerreteriaApp.bdatosfer
{

    [Persistent(@"venta")]
    public partial class Venta : XPLiteObject
    {
        int fIdVenta;
        [Key(true)]
        public int IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<int>(nameof(IdVenta), ref fIdVenta, value); }
        }
        Usuario fIdUsuario;
        [Association(@"VentaReferencesUsuario")]
        public Usuario IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<Usuario>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        Cliente fIdCliente;
        [Association(@"VentaReferencesCliente")]
        public Cliente IdCliente
        {
            get { return fIdCliente; }
            set { SetPropertyValue<Cliente>(nameof(IdCliente), ref fIdCliente, value); }
        }
        decimal fMontoPago;
        public decimal MontoPago
        {
            get { return fMontoPago; }
            set { SetPropertyValue<decimal>(nameof(MontoPago), ref fMontoPago, value); }
        }
        decimal fMontoCambio;
        public decimal MontoCambio
        {
            get { return fMontoCambio; }
            set { SetPropertyValue<decimal>(nameof(MontoCambio), ref fMontoCambio, value); }
        }
        decimal fMontoTotal;
        public decimal MontoTotal
        {
            get { return fMontoTotal; }
            set { SetPropertyValue<decimal>(nameof(MontoTotal), ref fMontoTotal, value); }
        }
        [Association(@"Detalle_ventaReferencesVenta")]
        public XPCollection<Detalle_venta> Detalle_ventas { get { return GetCollection<Detalle_venta>(nameof(Detalle_ventas)); } }
    }

}
